# Generated by Django 6.0.6 on 2026-07-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0002_equipo_ingeniero_sala_remove_libro_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='capacidad',
        ),
        migrations.AddField(
            model_name='sala',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='salas/'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='precio_hora',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
