# Generated by Django 6.0.6 on 2026-07-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0004_equipo_comprobante_equipo_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingeniero',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
