# Generated by Django 6.0.6 on 2026-07-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0005_ingeniero_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingeniero',
            name='precio_hora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
