# Generated by Django 6.0.6 on 2026-07-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0006_ingeniero_precio_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='comprobante',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='precio_alquiler',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
